### ISSUE TITLE
Adapt tests from python version of XGBoost

### ISSUE THREAD

**Issue by maximsch2** [dmlc/XGBoost.jl#16]
XGBoost.jl was recently broken due to the update in the dmlc/xgboost (which is fixed now by #12). While this wouldn't necessarily catch it, having tests similar to https://github.com/dmlc/xgboost/tree/master/tests/python will be very helpful

**Comment by tqchen** [comment]
There was a few tests in https://github.com/dmlc/XGBoost.jl/tree/master/test contributed by @slundberg  I think we only need to setup a formal travis CI to continuously check the results for each PR and also make the testcase more organized, contribution is welcomed

**Comment by slundberg** [comment]
I agree that better tests would be useful. The file I used for testing was just the file showing example use cases, it either crashes or runs, rather than checking for accuracy.

@tqchen could you flip the dmlc Travis CI account switch for this repo? Then we could just stick the badge on the readme and add better tests as they get written.

**Comment by tqchen** [comment]
@slundberg travis is now on

**Comment by slundberg** [comment]
thanks!

**Comment by maximsch2** [comment]
Awesome! I've just fixed the .travis.yml so that Travis now actually builds XGBoost and runs tests #18. I can add some basic tests after it is merged.

**Comment by maximsch2** [comment]
I'll close this for now as we have some tests up and running now. Thanks @tqchen for merging them!
