### ISSUE TITLE
Is support for GPU available using parameters?

### ISSUE THREAD

**Issue by caxelrud** [dmlc/XGBoost.jl#70]
Is it possible to use parameters as "tree_method= gpu_hist"?
Are examples available?

**Comment by dpk1729** [comment]
In order to be able to train on gpu, you should first compile xgboost with cuda flag and then replace the `.so` file in your julia packages folder with this new file. Here's how you can do that

Clone xgboost repo, and pull the submodules

```
git clone https://github.com/dmlc/xgboost.git
cd xgboost/
git submodule update --init --recursive
```

Build xgboost
```
mkdir build
cd build
cmake .. -DUSE_CUDA=ON
make -j4
```
This creates a `libxgboost.so` file in the `lib` folder.
Copy this file to the XGBoost package directory to the location where julia installed xgboost
`cp xgboost/lib/libxgboost.so .julia/packages/XGBoost/...../deps/usr/lib`

After this you should be able to train on gpu with 
`bst = xgboost(data, ....,tree_method="gpu_hist")`

**Comment by caxelrud** [comment]
I am using Windows 10. 
I got the dll from this site:
https://picnet.com.au/blog/xgboost-windows-x64-binaries-for-download/
And replaced at the Julia package location.
It is not complaining when using method="gpu_hist" so it looks like is working.

**Comment by aviks** [comment]
closing this issue, this is the way to do this for now.

**Comment by john-b-edwards** [comment]
Is this still the recommended means of running xgboost with `gpu_hist`? Installing `XGBoost.jl` I don't see a `.so` file to replace in the package.
