### ISSUE TITLE
Hyperparameter Tuning

### ISSUE THREAD

**Issue by Sinansi** [dmlc/XGBoost.jl#80]
Hello,

May someone confirm whether this package support hyperparameter tuning?
Either grid or random search? If not, any plan to add it in the future?

Thank you!

**Comment by ablaom** [comment]
XGBoost is a model supported by the [MLJ.jl](https://github.com/alan-turing-institute/MLJ.jl) machine learning platform which, among other things, allows you to tune models with a grid search (more options coming soon). 

You can look at this XGBoost [example](https://github.com/alan-turing-institute/MLJ.jl/blob/master/examples/xgboost.jl) but note that the tuning API has changed a little since that was written (specifically, how you specify the range). See [here](https://alan-turing-institute.github.io/MLJ.jl/dev/tuning_models/)  and [here](https://alan-turing-institute.github.io/MLJTutorials/pub/getting-started/model-tuning.html) for the latest API

**Comment by ablaom** [comment]
Okay, there is an up-to-date XGBoost tuning example [here](https://alan-turing-institute.github.io/MLJTutorials/pub/end-to-end/crabs-xgb.html).

**Comment by ablaom** [comment]
You may also want  to check out [EvoTrees.jl](https://github.com/Evovest/EvoTrees.jl), a pure julia alternative to XGBoost for which an MLJ interface is a work-in-progress.

**Comment by Sinansi** [comment]
Dear Dr. Anthony,
Thanks alot for your great help. This package seems promising. I was just going to ask you about hyper tuning it, but I saw your comment regarding integrating it with MLJ. I can't wait to fully utilize this package. Looking forward to MLJ future releases. Thanks again!
